# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CurviCoordDialog
                                 A QGIS plugin
 Plugin for river data conversion from Cartesian to curvilinear orthogonal system
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-05-24
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Sergei Freiman
        email                : freimansgy@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'curvilinear_coordinator_dialog_base.ui'))
    
# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS_bp_warn, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'curvilinear_coordinator_dialog_base.ui'))


class CurviCoordDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(CurviCoordDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

class Bounding_polygone_warning(QtWidgets.QDialog, FORM_CLASS_bp_warn):
    def __init__(self, parent=None):
        """Constructor."""
        super(Bounding_polygone_warning, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)